name: CI

on:
  push:
    branches: [ mawa ]
  pull_request:
    branches: [ mawa ]

jobs:
    repoman:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: lucianposton/repoman-ebuild-qa-action@v1
              with:
                repoman_args: -dI
                portage_version: latest
